### PR TITLE
Handle flatten fields with nullable parents

### LINKED ISSUE #33: Flatten step potentially creates corrupted avro records
To reproduce: (in docker env) 

docker-compose.yaml
```
postgres:
    image: postgres:14.3
    container_name: postgres
    networks: [ "net1" ]
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
```

1. Setup postgre debezium source with avro converter
```
docker-compose up -d postgres

docker exec -it postgres psql -U postgres -c 'create table if not exists pulsar_table_source (key VARCHAR(255) PRIMARY KEY, value VARCHAR(255) NULL);' postgres



docker exec -it pulsar bin/pulsar-admin sources create --namespace default --tenant public \
    --source-type  debezium-postgres \
    --destination-topic-name debezium-postgres-topic \
    --name pg-source \
    --source-config '{"key.converter": "org.apache.pulsar.kafka.shade.io.confluent.connect.avro.AvroConverter", "value.converter": "org.apache.pulsar.kafka.shade.io.confluent.connect.avro.AvroConverter", "plugin.name": "pgoutput","database.hostname": "postgres", "database.user": "postgres", "database.server.name": "dbserver1", "database.password": "password", "database.dbname": "postgres", "schema.whitelist": "public", "pulsar.service.url": "pulsar://pulsar:6650" }' \
    --parallelism 1

docker exec -it postgres bash -c "psql -U postgres -c \"insert into pulsar_source_table(key,value) select left(md5(i::text), 10),i from generate_series(1, 10) s(i)\""

```

2. Create a sink (in my case a Pulsar Sink) with the transforms fn attached
```
docker exec -it pulsar bin/pulsar-admin sinks create --namespace default --tenant public \
    --sink-type cassandra-enhanced \
    --name cassandra-sink \
    --inputs dbserver1.public.pulsar_source_table \
    --subs-position Earliest \
    --sink-config '{"verbose": true, "tasks.max":1,"topics":"dbserver1.public.pulsar_source_table","contactPoints":"cassandra","loadBalancing.localDc":"datacenter1","port":9042,"cloud.secureConnectBundle":null,"ignoreErrors":"None","maxConcurrentRequests":500,"maxNumberOfRecordsInBatch":32,"queryExecutionTimeout":30,"connectionPoolLocalSize":4,"jmx":true,"compression":"None","auth":{"provider":"None","username":null,"password":null,"gssapi":{"keyTab":null,"principal":null,"service":"dse"}},"ssl":{"provider":"None","hostnameValidation":true,"keystore":{"password":null,"path":null},"openssl":{"keyCertChain":null,"privateKey":null},"truststore":{"password":null,"path":null},"cipherSuites":null},"topic":{"dbserver1.public.pulsar_source_table":{"baselines":{"pgsourcetable":{"mapping":"key=key.key, value=value.myvalue","consistencyLevel":"LOCAL_ONE","ttl":-1,"ttlTimeUnit":"SECONDS","timestampTimeUnit":"MICROSECONDS","nullToUnset":true,"deletesEnabled":true}},"codec":{"locale":"en_US","timeZone":"UTC","timestamp":"CQL_TIMESTAMP","date":"ISO_LOCAL_DATE","time":"ISO_LOCAL_TIME","unit":"MILLISECONDS"}}}}' \
    --parallelism 1 \
    --transform-function builtin://transform \
    --transform-function-config '{"steps": [{"type": "flatten", "part": "value"}]}'
```
Then you get this error in the sink
```
org.apache.pulsar.client.api.SchemaSerializationException: java.io.EOFException
        at org.apache.pulsar.client.impl.schema.generic.GenericAvroReader.read(GenericAvroReader.java:91) ~[?:?]
        at org.apache.pulsar.client.impl.schema.generic.GenericAvroReader.read(GenericAvroReader.java:41) ~[?:?]
        at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:40) ~[java-instance.jar:?]
        at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.read(AbstractMultiVersionReader.java:89) ~[?:?]
        at org.apache.pulsar.client.impl.schema.AbstractStructSchema.decode(AbstractStructSchema.java:66) ~[?:?]
        at org.apache.pulsar.client.impl.schema.KeyValueSchemaImpl.decode(KeyValueSchemaImpl.java:180) ~[?:?]
        at org.apache.pulsar.client.impl.schema.KeyValueSchemaImpl.lambda$decode$0(KeyValueSchemaImpl.java:161) ~[?:?]
        at org.apache.pulsar.common.schema.KeyValue.decode(KeyValue.java:146) ~[java-instance.jar:?]
        at org.apache.pulsar.client.impl.schema.KeyValueSchemaImpl.decode(KeyValueSchemaImpl.java:161) ~[?:?]
        at org.apache.pulsar.client.impl.schema.KeyValueSchemaImpl.decode(KeyValueSchemaImpl.java:43) ~[?:?]
        at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:120) ~[?:?]
        at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:48) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.encodeWithRecordSchemaAndDecodeWithSinkSchema(JavaInstanceRunnable.java:459) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.sendOutputMessage(JavaInstanceRunnable.java:416) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.handleResult(JavaInstanceRunnable.java:394) ~[?:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:335) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.io.EOFException
        at [org.apache.avro.io](http://org.apache.avro.io/).BinaryDecoder$ByteArrayByteSource.readRaw(BinaryDecoder.java:999) ~[java-instance.jar:?]
        at [org.apache.avro.io](http://org.apache.avro.io/).BinaryDecoder.doReadBytes(BinaryDecoder.java:405) ~[java-instance.jar:?]
        at [org.apache.avro.io](http://org.apache.avro.io/).BinaryDecoder.readString(BinaryDecoder.java:313) ~[java-instance.jar:?]
        at [org.apache.avro.io](http://org.apache.avro.io/).ResolvingDecoder.readString(ResolvingDecoder.java:208) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:469) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:459) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:191) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:259) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:247) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:179) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:160) ~[java-instance.jar:?]
        at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153) ~[java-instance.jar:?]
        at org.apache.pulsar.client.impl.schema.generic.GenericAvroReader.read(GenericAvroReader.java:86) ~[?:?]
        ... 16 more
```

Notes:
1. If I remove the transform function, the sink is able to read the record coming from the debezium source
2. I use the Avro format because JSON is not supported by the flatten step (perhaps we should track an issue)
3. My first assumption is that the output schema is not keeping the schema props. the debezium source set a special prop "__AVRO_READ_OFFSET__" to 5. This is used in Pulsar to set the start offset for reading the record. I don't know why and it may cause such error btw

### PR DESCRIPTION
**Pull request by aymkhalil**
fixes #33 

The main bugs fixed:
1. When generating the flattened field, if any parent field schema is nullable, mark the flattened field schema as nullable because at runtime, any ancestor could be null.
2. Use the original schema to traverse the recursion tree and avoid reflection on the actual GenericRecord value because if this was null, it'll cause the final flattened schema to be trimmed at the null levels prematurely. In other words, decouple the traversal of the schema from the the fields value.
3. Fix issues an issue in aliases copy
4. For now, skip copying the `__AVRO_READ_OFFSET__` property, It causes issues when the input schema is key/value, but the flatten is called only on the key or value part. Need more analysis about the usage of  `__AVRO_READ_OFFSET__`

### CODE REVIEW

File: pulsar-transformations/src/main/java/com/datastax/oss/pulsar/functions/transforms/FlattenStep.java [hunk 1]
```diff
@@ -97,49 +102,102 @@ private List<FieldValuePair> buildFlattenedFields(GenericRecord record) {
...
 
     return flattenedFields;
   }
 
+  private org.apache.avro.Schema getRecordSchema(org.apache.avro.Schema schema, String name) {
+    if (schema.getType() != org.apache.avro.Schema.Type.RECORD) {
+      return null;
+    }
+
+    if (schema.getField(name).schema().isUnion()) {
```
Comment (eolivelli) [inline pulsar-transformations/src/main/java/com/datastax/oss/pulsar/functions/transforms/FlattenStep.java:173]: nit:
we can save some cycles by calling "schema.getField(name)" only once

**Review by eolivelli — APPROVED** [review]
LGTM

I have left one suggestion, PTAL

**Review by nicoloboschi — APPROVED** [review]
